---
all:
  vars:
    #cartridge_package_path: "../../packages/tdg-ENTER-VERSION-HERE.tar.gz" # path relative to playbook
    #cartridge_cluster_cookie: "ENTER-SECRET-COOKIE-HERE"

    ansible_user: "vagrant"
    ansible_ssh_pipelining: true
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    cartridge_app_name: "tdg"
    cartridge_bootstrap_vshard: true
    cartridge_failover_params:
      mode: "stateful"
      state_provider: "stateboard"
      stateboard_params:
        uri: "172.19.0.2:3300"
        password: "tdg-stateboard-pass"

    # Here you can change Cartridge arguments for all instances:
    #cartridge_defaults:
    #  memtx_memory: 33554432  # 32 Mb
    #  vinyl_memory: 0
    #  vinyl_cache: 0
    #  readahead: 16320

  children:
    tdg_group:

      ### Instances ###

      hosts:
        stateboard_instance:
          stateboard: true
          config:
            listen: "0.0.0.0:3300"
            password: "tdg-stateboard-pass"

        core:
          config:
            advertise_uri: "172.19.0.2:3001"
            http_port: 8081
            memtx_memory: 134217728  # 128 Mb

        runner_1:
          config:
            advertise_uri: "172.19.0.2:3002"
            http_port: 8082
            memtx_memory: 134217728  # 128 Mb

        storage_1:
          config:
            advertise_uri: "172.19.0.2:3003"
            http_port: 8083
            memtx_memory: 1073741824  # 1024 Mb

        storage_2:
          config:
            advertise_uri: "172.19.0.2:3004"
            http_port: 8084
            memtx_memory: 1073741824  # 1024 Mb

        runner_2:
          config:
            advertise_uri: "172.19.0.3:3001"
            http_port: 8081
            memtx_memory: 134217728  # 128 Mb

        storage_1_replica:
          config:
            advertise_uri: "172.19.0.3:3002"
            http_port: 8082
            memtx_memory: 1073741824  # 1024 Mb

        storage_2_replica:
          config:
            advertise_uri: "172.19.0.3:3003"
            http_port: 8083
            memtx_memory: 1073741824  # 1024 Mb

      children:

        ### Machines ###

        vm1:
          hosts:
            stateboard_instance:
            core:
            runner_1:
            storage_1:
            storage_2:
          vars:
            ansible_host: "172.19.0.2"

        vm2:
          hosts:
            runner_2:
            storage_1_replica:
            storage_2_replica:
          vars:
            ansible_host: "172.19.0.3"

        ### Replica Sets ###

        replica_set_core:
          hosts:
            core:
          vars:
            replicaset_alias: "core"
            failover_priority:
              - "core" # master
            roles:
              - "core"

        replica_set_runner_1:
          hosts:
            runner_1:
          vars:
            replicaset_alias: "runner_1"
            failover_priority:
              - "runner_1" # master
            roles:
              - "failover-coordinator"
              - "connector"
              - "runner"

        replica_set_runner_2:
          hosts:
            runner_2:
          vars:
            replicaset_alias: "runner_2"
            failover_priority:
              - "runner_2" # master
            roles:
              - "connector"
              - "runner"

        replica_set_storage_1:
          hosts:
            storage_1:
            storage_1_replica:
          vars:
            replicaset_alias: "storage_1"
            failover_priority:
              - "storage_1" # master
              - "storage_1_replica"
            roles:
              - "storage"

        replica_set_storage_2:
          hosts:
            storage_2:
            storage_2_replica:
          vars:
            replicaset_alias: "storage_2"
            failover_priority:
              - "storage_2" # master
              - "storage_2_replica"
            roles:
              - "storage"
