$ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

$script = <<-SCRIPT
set -e
yum -y install ntp htop ncdu
systemctl enable ntpd
systemctl start ntpd

echo #{$ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys

mkdir -p /var/lib/core_dumps
chmod 777 /var/lib/core_dumps
echo 'kernel.core_pattern = /var/lib/core_dumps/%e.time_%t.signal_%s.pid_%p' >> /etc/sysctl.conf

cat <<EOF >> /etc/systemd/journald.conf
Storage=persistent
SystemMaxUse=5G
SystemKeepFree=1G
RuntimeMaxUse=1G
RuntimeKeepFree=512M
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.define "vm1" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.network "private_network", ip: "172.19.0.2"
    cfg.vm.hostname = 'vm1'
  end

  config.vm.define "vm2" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.network "private_network", ip: "172.19.0.3"
    cfg.vm.hostname = 'vm2'
  end

  config.vm.provision :shell, inline: $script
end
